baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Bible Believers Western Cape'

[module]
  [[module.imports]]
    path = "github.com/Lednerb/bilberry-hugo-theme"
    disable = false
  [[module.imports.mounts]]
    source = "bbwc"
    target = "assets/bbwc"
